# Generated by Django 5.1.6 on 2026-02-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('aicte_id', models.CharField(blank=True, default='', max_length=100)),
                ('inst_type', models.CharField(default='Engineering', max_length=100)),
                ('category', models.CharField(default='Affiliated', max_length=100)),
                ('year_established', models.IntegerField(default=2000)),
                ('affiliated_univ', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('principal_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DisclosureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('faculty', 'Faculty Details'), ('labs', 'Laboratory Details'), ('infrastructure', 'Infrastructure'), ('students', 'Student Details'), ('financials', 'Financial Details'), ('accreditation', 'Accreditation')], max_length=50)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('pdf_file', models.FileField(upload_to='disclosure_pdfs/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('ai_response', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Analyzed', max_length=30)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='aicteapproval.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, default='AICTE Authority', max_length=255)),
                ('authority_notes', models.TextField(blank=True, default='')),
                ('risk_score_at_submission', models.IntegerField(default=0)),
                ('risk_level_at_submission', models.CharField(default='', max_length=20)),
                ('risk_factors_at_submission', models.JSONField(default=list)),
                ('sections_submitted', models.JSONField(default=list)),
                ('section_decisions', models.JSONField(default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='aicteapproval.institution')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('compliance_pct', models.FloatField(default=100.0)),
                ('faculty_shortage', models.BooleanField(default=False)),
                ('infra_deficit', models.BooleanField(default=False)),
                ('expired_certs', models.BooleanField(default=False)),
                ('faculty_ratio', models.FloatField(default=0.0)),
                ('risk_factors', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('section_scores', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='aicteapproval.disclosuresection')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='aicteapproval.institution')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_faculty', models.IntegerField(default=0)),
                ('required_faculty', models.IntegerField(default=0)),
                ('faculty_phd_count', models.IntegerField(default=0)),
                ('faculty_details', models.JSONField(default=list)),
                ('total_labs', models.IntegerField(default=0)),
                ('lab_details', models.JSONField(default=list)),
                ('total_classrooms', models.IntegerField(default=0)),
                ('library_books', models.IntegerField(default=0)),
                ('computer_count', models.IntegerField(default=0)),
                ('total_area_sqft', models.IntegerField(default=0)),
                ('hostel_capacity', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('ug_students', models.IntegerField(default=0)),
                ('pg_students', models.IntegerField(default=0)),
                ('programs_offered', models.JSONField(default=list)),
                ('annual_budget', models.FloatField(default=0.0)),
                ('fee_structure', models.JSONField(default=dict)),
                ('naac_grade', models.CharField(blank=True, default='', max_length=10)),
                ('nba_programs', models.CharField(blank=True, default='', max_length=10000)),
                ('iso_certified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='aicteapproval.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('warning', 'Warning'), ('success', 'Success'), ('danger', 'Danger'), ('info', 'Info')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='aicteapproval.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
